// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr-YshTylwlvJpZi8YyzgOTBiy_c6N7xw',
    appId: '1:209773805623:web:bba67320d9f71dad9bffb2',
    messagingSenderId: '209773805623',
    projectId: 'task-basic',
    authDomain: 'task-basic.firebaseapp.com',
    storageBucket: 'task-basic.appspot.com',
    measurementId: 'G-90LLJ1WSG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjIfmJJGPWrSoG1fKsVNIwb9_S-ijFCI',
    appId: '1:209773805623:android:f0e83cc7bc91b50f9bffb2',
    messagingSenderId: '209773805623',
    projectId: 'task-basic',
    storageBucket: 'task-basic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbwGX2cNDp8dlatYGUnsmmf5C8Fkq4xws',
    appId: '1:209773805623:ios:72d648e593c5592c9bffb2',
    messagingSenderId: '209773805623',
    projectId: 'task-basic',
    storageBucket: 'task-basic.appspot.com',
    androidClientId: '209773805623-a3lt4m1bbiusphdvejesrmt88t0gpv9h.apps.googleusercontent.com',
    iosClientId: '209773805623-n42t8puiddoi18jike918ts6nlf8d4j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbwGX2cNDp8dlatYGUnsmmf5C8Fkq4xws',
    appId: '1:209773805623:ios:a47f1f38c2b58a269bffb2',
    messagingSenderId: '209773805623',
    projectId: 'task-basic',
    storageBucket: 'task-basic.appspot.com',
    androidClientId: '209773805623-a3lt4m1bbiusphdvejesrmt88t0gpv9h.apps.googleusercontent.com',
    iosClientId: '209773805623-j1ap3ev5iq5adtlp6o5m3p57lhpuksv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksBasic.RunnerTests',
  );
}
